app = "mandelbrot-stream"

[build]
  # This tells Fly.io to use the Dockerfile for building the app
  builder = "docker"

[[services]]
  internal_port = 3000  # The port your app will listen on
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 80
    handlers = ["http"]  # Optional: Expose HTTP


