app = "mandelbrot-stream"

[build]
  builder = "heroku/buildpacks:nodejs"  # Optional, for Node.js
  # Use Nixpacks builder explicitly
  [build.nixpacks]
    # Nixpacks will automatically handle dependencies such as Node.js and FFmpeg.
    buildpacks = [
      "heroku/nodejs"  # for Node.js apps
    ]
    hooks = ["apt-get update && apt-get install -y ffmpeg"]  # Install FFmpeg

[env]
  FFMPEG_PATH = "/usr/bin/ffmpeg"  # Path to FFmpeg

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 80
    handlers = ["http"]

